backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/image"
public_folder: "/assets/image"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Illustration", name: "image", widget: "image" }
      - { label: "Légende", name: "imageAlt", widget: "string" }
      - { label: "Texte", name: "body", widget: "markdown" }